build:
  stage: build
  script:
    - docker build -t $DOCKER_REGISTRY_URL/lul-registry/lul-web-bff .
    - mkdir ~/.docker
    - cat $DOCKER_CREDS > ~/.docker/config.json    
    - docker login $DOCKER_REGISTRY_URL
    - docker push $DOCKER_REGISTRY_URL/lul-registry/lul-web-bff
