version: "3.9"
services:
    web-bff:
      build: .
      environment:
        DB_CONNECTION_STRING: mongodb+srv://admin:admin@cluster0.2mmi2.mongodb.net/LUL?retryWrites=true&w=majority
        PORT: 4000
        JWT_ACCESS_SECRET: random string
        JWT_SESSION_SECRET: random string2
      ports: 
        - '${PORT}:${PORT}'